export const recipes = [
  {
    id: '01',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 3.0,
  },
  {
    id: '02',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 4.1,
  },
  {
    id: '03',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 4.6,
  },
  {
    id: '04',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 4.2,
  },
  {
    id: '05',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 3.8,
  },
  {
    id: '06',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 4.5,
  },
  {
    id: '07',
    name: 'Tuna Tartare',
    image: require('../../assets/images/recipe1.png'),
    ingredients: [],
    time: '40 minutes',
    difficulty: 'Medium',
    calories: '420 cal',
    rating: 4.0,
  },
];
